kind: pipeline
name: default

steps:
- name: publish-to-docker
  image: plugins/docker
  settings:
    repo: nint8835/rileyflynn.me
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - DRONE_COMMIT=${DRONE_COMMIT}
      - DRONE_COMMIT_LINK=${DRONE_COMMIT_LINK}
  when:
    branch:
      - master
    event:
      - push
      - tag