baseURL = "https://rileyflynn.me"
languageCode = "en-us"
title = "Riley Flynn - Software Developer"
theme = "dimension"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'I am a second year computer science student at <a href="https://www.mun.ca">Memorial University of Newfoundland</a><br/>and Vice President of the <a href="https://muncompsci.ca">MUN Computer Science Society</a>'
  logo = "fa-terminal"
  copyright = "Riley Flynn. Picture of St. John's provided by Jack Harrhy"
  images = ["images/bg.jpg"]