name: Deploy to GHCR (Dev)

on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GHCR (Dev)
      uses: docker/build-push-action@v1
      with:
        repository: nint8835/rileyflynn.me
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tags: dev
